// Changelog from git history (PRD FEAT-04). Every merge to main is one squash
// commit named for its pull request, "TPL-05: Word downloads ... (#19)", so the
// first-parent history of main is the project's change history. No file or git
// access here, so npm test can run it; scripts/build-changelog.mjs feeds it.

// Change types, from the start of the commit subject, in display order.
export const TYPES = [
	['feature', 'Site and template kit', /^(?:CTRL|TPL|PROG|NAV|LINK|PRES|QA|FEAT|SSDF)-\d+/],
	['content', 'Content', /^Content:/],
	['dependency', 'Dependencies', /^(?:Bump|build\(deps|chore\(deps)/i],
	['project', 'Project notes', /^(?:Progress|PRD|Docs?)\b/],
	['other', 'Other changes', /./],
];

const MONTHS = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'];

/**
 * @param line "<sha>\x1f<ISO date>\x1f<subject>\x1f<ref names>" from git log
 * @returns { sha, date, subject, pr, tags, type }
 */
export function parseCommit(line) {
	const [sha, date, rawSubject, refs = ''] = line.split('\x1f');
	const m = rawSubject.match(/^(.*?)\s*\(#(\d+)\)$/);
	const subject = m ? m[1] : rawSubject;
	const tags = refs
		.split(',')
		.map((r) => r.trim())
		.filter((r) => r.startsWith('tag: '))
		.map((r) => r.slice(5))
		.filter((t) => /^v\d+\.\d+\.\d+$/.test(t));
	const type = TYPES.find(([, , re]) => re.test(subject))[0];
	return { sha, date: date.slice(0, 10), subject, pr: m ? Number(m[2]) : null, tags, type };
}

/**
 * Groups commits (newest first) into sections. With release tags (vX.Y.Z), a
 * section per release plus "Unreleased" for newer commits; without, a section
 * per month.
 */
export function sections(commits) {
	if (!commits.some((c) => c.tags.length)) {
		const byMonth = new Map();
		for (const c of commits) {
			const [y, mo] = c.date.split('-');
			const key = `${MONTHS[Number(mo) - 1]} ${y}`;
			if (!byMonth.has(key)) byMonth.set(key, []);
			byMonth.get(key).push(c);
		}
		return [...byMonth].map(([title, list]) => ({ title, commits: list }));
	}
	const out = [];
	let current = { title: 'Unreleased', commits: [] };
	for (const c of commits) {
		if (c.tags.length) {
			if (current.commits.length || current.title !== 'Unreleased') out.push(current);
			current = { title: `${c.tags[0]} (${c.date})`, version: c.tags[0], commits: [] };
		}
		current.commits.push(c);
	}
	out.push(current);
	return out;
}

const escape = (s) => s.replace(/([\\`*_[\]<>|])/g, '\\$1');

const cap = (s) => s.charAt(0).toUpperCase() + s.slice(1);

function entry(c, repoUrl) {
	// "TPL-05: ...", "PROG-01, PROG-05: ...", "CTRL-01 to CTRL-03: ..."
	const id = c.subject.match(/^([A-Z]+-\d+(?:(?:,\s*|\s+to\s+)[A-Z]+-\d+)*):\s*(.*)$/);
	const text = id ? `**${id[1]}** ${escape(cap(id[2]))}` : escape(cap(c.subject.replace(/^Content:\s*/, '')));
	const link = c.pr ? ` ([#${c.pr}](${repoUrl}/pull/${c.pr}))` : '';
	return `- ${text}${link}`;
}

// One section's notes: an h3 per change type, entries newest first.
export function sectionNotes(section, repoUrl) {
	return TYPES.map(([type, label]) => {
		const list = section.commits.filter((c) => c.type === type);
		return list.length ? [`### ${label}`, '', ...list.map((c) => entry(c, repoUrl))].join('\n') : '';
	})
		.filter(Boolean)
		.join('\n\n');
}

export function changelogPage(commits, { repoUrl, shallow = false }) {
	const body = sections(commits)
		.map((s) => `## ${s.title}\n\n${sectionNotes(s, repoUrl)}`)
		.join('\n\n');
	return [
		'---',
		"title: 'Changelog'",
		"description: 'Every change to the RMF Field Guide and its template kit, generated from the site history on each deploy.'",
		'editUrl: false',
		'sidebar:',
		'  order: 90',
		'---',
		'',
		'<!-- Generated by scripts/build-changelog.mjs at build time from git history. Not committed; do not edit. -->',
		'',
		`Every change to the guide and the template kit, newest first. Each entry is one merged pull request; the ID at its start is the requirement it delivers. The page is rebuilt from the [project history](${repoUrl}/commits/main/) whenever a change is published${commits.some((c) => c.tags.length) ? ', and each kit release has its own section' : '. Kit releases will get their own sections once the first version is tagged'}. Content marked draft has not yet been reviewed by the author.`,
		'',
		shallow ? ':::note\nThis build had only part of the history available, so older changes are missing.\n:::\n' : '',
		body,
		'',
	]
		.filter((l, i, a) => l !== '' || a[i - 1] !== '')
		.join('\n');
}
