// Builds the generated template pages under src/content/docs/templates/
// (PRD TPL-07) and names the download files, so pages and kit agree.
// No file access, so npm test can run it on fixtures.
import { assemblePolicy, inSecurityBaseline, ORGANIZATION, policyBaselines } from '../../src/lib/template-assemble.ts';
import { renderBlocks } from '../../src/lib/template-editions.ts';
import { renderVariables } from '../../src/lib/template-vars.ts';
import { WORKSHEET_COLUMNS, worksheetRows } from '../../src/lib/template-worksheet.ts';

export const GENERATED_NOTE =
	'<!-- Generated by npm run templates from templates/. Edit the sources there, not this page. -->';
export const PREVIEW_BASELINE = 'Moderate';
const EDITION_SUFFIX = { clean: '', annotated: '-annotated' };
const TYPE_LABEL = { policy: 'Policy', plan: 'Plan', standard: 'Standard', procedure: 'Procedure', form: 'Form or register', report: 'Report', worksheet: 'Decision worksheet' };
const TYPE_GROUP = {
	policy: 'Policies',
	worksheet: 'Decision worksheets',
	plan: 'Plans',
	standard: 'Standards',
	procedure: 'Procedures',
	form: 'Forms and registers',
	report: 'Reports',
};

// A family SP 800-53B allocates to no baseline (PM): one organization-wide variant.
export const organizationWide = (family) => family.baseline === 'none';
// The family's own common sections, or the ones every family policy shares.
export const commonFor = (family, common) => family.common ?? common;

// A role label as it reads inside a sentence, where _common.md puts "The"
// before the field: a title-case title ("Chief Information Security Officer")
// keeps its capitals; a sentence-case label ("Senior privacy official") starts
// lowercase.
export const roleInSentence = (label) =>
	/^[A-Z][a-z]*(?: [A-Z][a-z]*)+$/.test(label) ? label : label.charAt(0).toLowerCase() + label.slice(1);

// Typical values from the family's common sections, keyed by the family's own
// parameter ids. The shared policy/_common.md keys them "xx-01_odp.01", as its
// {{param:xx-...}} fields; xx becomes the family id. The shared sections leave
// the -1 managing official (xx-01_odp.04) without a value: it defaults to the
// role accountable for the family policy (_family.yml `role`), the same role
// the decision worksheet names under "Who decides".
export function commonTypical(family, common, variables = {}) {
	const source = commonFor(family, common);
	const typical = Object.fromEntries(
		Object.entries(source?.data?.typical ?? {}).map(([id, v]) => [id.startsWith('xx-') ? family.id + id.slice(2) : id, v]),
	);
	const official = `${family.id}-01_odp.04`;
	if (!family.common && source && !typical[official]) typical[official] = roleInSentence(variables[family.role]?.label ?? family.role);
	return typical;
}
const variantLabel = (b) => (b === ORGANIZATION ? 'Organization-wide' : b);

const yaml = (s) => `'${String(s).replace(/'/g, "''")}'`;
const cap = (s) => s.charAt(0).toUpperCase() + s.slice(1);
const controlUrl = (id) => {
	const [base, enh] = id.split('.');
	return `/controls/${base.split('-')[0]}/${base}/${enh ? `#${id}` : ''}`;
};

// Download paths under /downloads/, without extension.
export const policyFile = (family, baseline, edition) =>
	`policies/${family}-policy-${baseline.toLowerCase()}${EDITION_SUFFIX[edition]}`;
export const templateFile = (id, edition) => `${id}${EDITION_SUFFIX[edition]}`;
export const worksheetFile = (family, baseline) => `worksheets/${family}-decisions-${baseline.toLowerCase()}`;
// Zips, with extension.
export const packFile = (family) => `packs/${family}-pack.zip`;
export const KIT_FILE = 'rmf-field-guide-kit.zip';

// Site preview: annotated edition, headings one level down under "## Preview",
// without the document's own title.
export function preview(source, ctx) {
	return renderVariables(renderBlocks(source, 'annotated', 'site'), ctx, 'site')
		.replace(/^# .*\n+/, '')
		.replace(/^(#{1,5}) /gm, '#$1 ')
		.trim();
}

function facts({ type, stage, status, version, basis }) {
	return [
		'| Type | Program stage | Status | Template version | NIST basis |',
		'| --- | --- | --- | --- | --- |',
		`| ${TYPE_LABEL[type]} | [${cap(stage)}](/program/${stage}/) | ${cap(status)} | ${version} | ${basis} |`,
	].join('\n');
}

function page({ title, description, label, order, controls, body }) {
	return [
		'---',
		`title: ${yaml(title)}`,
		`description: ${yaml(description)}`,
		'sidebar:',
		`  label: ${yaml(label)}`,
		`  order: ${order}`,
		`controls: [${controls.join(', ')}]`,
		'---',
		'',
		GENERATED_NOTE,
		'',
		// Weighted so searching a template's name finds the template before the
		// control page it serves (PRD NAV-01).
		`<p class="tpl-lead" data-pagefind-weight="10">${escapeHtml(title)} template: ${escapeHtml(description)}</p>`,
		'',
		body.trim(),
		'',
	].join('\n');
}

const escapeHtml = (s) => s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

const formats = (file) => `[Word](/downloads/${file}.docx) · [Markdown](/downloads/${file}.md)`;

function downloadRows(rows) {
	return [
		'| Variant | Ready to adopt | Annotated |',
		'| --- | --- | --- |',
		...rows.map(({ label, file }) => `| ${label} | ${formats(file('clean'))} | ${formats(file('annotated'))} |`),
	].join('\n');
}

/**
 * One family policy page: facts, what it is, controls, decisions, downloads per
 * baseline, and an annotated preview at the Moderate baseline.
 */
export function policyPage({ family, clauses, common, catalog, variables, version, order }) {
	const own = clauses.filter((c) => c.id.startsWith(`policy/${family.id}/`));
	const orgWide = organizationWide(family);
	const baselines = policyBaselines(family.id, own, catalog.controls, orgWide);
	const familyCommon = commonFor(family, common);
	const byId = new Map(catalog.controls.map((c) => [c.id, c]));
	const policyControl = byId.get(`${family.id}-1`);
	const fam = family.id.toUpperCase();
	const variants = Object.fromEntries(
		baselines.map((b) => [b, assemblePolicy({ common: familyCommon.body, family, clauses: own, controls: catalog.controls, baseline: b })]),
	);
	const shown = variants[PREVIEW_BASELINE] ?? Object.values(variants)[0];
	const shownBaseline = variants[PREVIEW_BASELINE] ? PREVIEW_BASELINE : baselines[0];
	const covered = [...new Set(Object.values(variants).flatMap((v) => v.controls))].sort(
		(a, b) => catalog.controls.findIndex((c) => c.id === a) - catalog.controls.findIndex((c) => c.id === b),
	);
	const params = new Set(
		covered.flatMap((id) => byId.get(id).params.filter((p) => !catalog.params[p].aggregates)),
	);
	const status = own.length && own.every((c) => c.status === 'reviewed') && familyCommon.data.status === 'reviewed' ? 'reviewed' : 'draft';

	const tick = (id, b) => (variants[b]?.controls.includes(id) ? 'Yes' : '');
	const controlRows = covered.map((id) => {
		const c = byId.get(id);
		const cells = orgWide ? [c.baselines.includes('Privacy') ? 'Yes' : ''] : ['Low', 'Moderate', 'High', 'Privacy'].map((b) => tick(id, b));
		return `| [${c.label}](${controlUrl(id)}) | ${c.title} | ${cells.join(' | ')} |`;
	});
	const controlTable = orgWide
		? ['| Control | Title | In the Privacy baseline |', '| --- | --- | --- |', ...controlRows]
		: ['| Control | Title | Low | Moderate | High | Privacy |', '| --- | --- | --- | --- | --- | --- |', ...controlRows];

	const questions = family.questions?.length
		? [
				'| Decision | Controls | Typical | Who decides |',
				'| --- | --- | --- | --- |',
				...family.questions.map(
					(q) =>
						`| ${q.question} | ${q.controls.map((id) => `[${byId.get(id).label}](${controlUrl(id)})`).join(', ')} | ${q.typical ?? ''} | ${q.decides} |`,
				),
			].join('\n')
		: '';

	const body = [
		facts({ type: 'policy', stage: family.stage, status, version, basis: catalog.source }),
		'## What it is',
		orgWide
			? `The ${family.title} policy states what the organization requires for ${family.title.toLowerCase()} and who is accountable for it. Its opening sections meet [${policyControl.label}](${controlUrl(policyControl.id)}), and it adds one statement group per control. NIST SP 800-53B allocates no ${fam} control to a security baseline: the organization carries them out once for all its systems, whatever their baselines. So this policy has one organization-wide edition, which every baseline's starter kit includes.`
			: `The ${family.title} policy states what the organization requires for ${family.title.toLowerCase()} and who is accountable for it. It meets [${policyControl.label}](${controlUrl(policyControl.id)}) through the sections every family policy shares, and adds one statement group per control. ${
					baselines.length === 1 && baselines[0] === 'Privacy'
						? `NIST SP 800-53B places every ${fam} control in the Privacy baseline and none in the Low, Moderate or High baselines, so this policy has one Privacy variant. Adopt it wherever systems process personally identifiable information, alongside the security baseline of each system.`
						: 'Each baseline variant includes only the controls in that baseline, taken from the NIST SP 800-53B profiles.'
				}`,
		'Adopt the ready-to-adopt edition: fill every highlighted field, delete any "Federal systems" section that does not apply, and have the accountable official approve it. The annotated edition adds guidance on why each section exists and what assessors look for.',
		'## Controls satisfied',
		orgWide
			? `The one edition has statements for every control listed. ${policyControl.label} is met by the opening sections. "Yes" marks the controls NIST also places in the Privacy baseline.`
			: `"Yes" marks the baseline variants that include the control's statements. ${policyControl.label} is met by the common sections.`,
		controlTable.join('\n'),
		'## Decisions to make first',
		`The policy has ${params.size} organization-defined parameters across all variants; each appears as a highlighted field with its typical value where one is given. Settle these first:`,
		questions || `No family-level decisions are recorded yet beyond the parameters.`,
		`Record your values in the [${family.title} decision worksheet](/templates/worksheets/${family.id}/), which lists every parameter with its typical value.`,
		'## Downloads',
		downloadRows(baselines.map((b) => ({ label: variantLabel(b), file: (e) => policyFile(family.id, b, e) }))),
		`Everything for this family in one file: [${fam} pack (.zip)](/downloads/${packFile(family.id)}), with every variant and edition of the policy and the decision worksheets.`,
		orgWide ? '## Preview (annotated)' : `## Preview (${shownBaseline} baseline, annotated)`,
		preview(shown.source, { variables, params: catalog.params, typical: { ...commonTypical(family, common, variables), ...shown.typical }, family }),
	]
		.filter(Boolean)
		.join('\n\n');

	return {
		file: `policies/${family.id}.md`,
		text: page({
			title: `${family.title} Policy`,
			description: `Ready-to-adopt ${family.title} policy template for NIST SP 800-53 Rev. 5, with a statement group for each control and ${orgWide ? 'one organization-wide edition' : `a variant per baseline (${baselines.join(', ')})`}.`,
			label: `${family.title} (${fam})`,
			order,
			controls: covered,
			body,
		}),
		summary: { title: `${family.title} Policy`, href: `/templates/policies/${family.id}/`, type: 'policy', stage: family.stage, status },
	};
}

/** One page for a plan, standard, procedure or form. */
export function templatePage({ template, catalog, variables, version, order }) {
	const byId = new Map(catalog.controls.map((c) => [c.id, c]));
	const rows = template.controls.map((id) => `| [${byId.get(id).label}](${controlUrl(id)}) | ${byId.get(id).title} |`);
	const body = [
		facts({ type: template.type, stage: template.stage, status: template.status, version, basis: catalog.source }),
		'## What it is',
		template.description,
		'## Controls satisfied',
		['| Control | Title |', '| --- | --- |', ...rows].join('\n'),
		template.ssdf?.length ? `**SSDF practices:** ${template.ssdf.join(', ')}` : '',
		'## Downloads',
		downloadRows([{ label: 'All baselines', file: (e) => templateFile(template.id, e) }]),
		template.type === 'form'
			? `The register as a spreadsheet: [CSV](/downloads/${templateFile(template.id, 'clean')}.csv), with one column per field.`
			: '',
		'## Preview (annotated)',
		preview(template.body, { variables, params: catalog.params, typical: template.typical }),
	]
		.filter(Boolean)
		.join('\n\n');
	const [folder, ...rest] = template.id.split('/');
	return {
		file: `${template.id}.md`,
		text: page({
			title: template.title,
			description: template.description,
			label: template.title,
			order,
			controls: template.controls,
			body,
		}),
		summary: { title: template.title, href: `/templates/${folder}/${rest.join('/')}/`, type: template.type, stage: template.stage, status: template.status },
	};
}

/** The templates index: every generated page, grouped by type. */
export function indexPage(summaries) {
	const groups = Object.keys(TYPE_GROUP)
		.map((type) => {
			const list = summaries.filter((s) => s.type === type);
			if (!list.length) return '';
			return [
				`## ${TYPE_GROUP[type]}`,
				['| Template | Program stage | Status |', '| --- | --- | --- |', ...list.map((s) => `| [${s.title}](${s.href}) | [${cap(s.stage)}](/program/${s.stage}/) | ${cap(s.status)} |`)].join('\n'),
			].join('\n\n');
		})
		.filter(Boolean);
	return [
		'---',
		"title: 'Templates'",
		"description: 'Ready-to-adopt security program templates for NIST SP 800-53 Rev. 5: family policies per baseline, plans, standards, procedures, forms and reports. CC0.'",
		'sidebar:',
		"  label: 'All templates'",
		'  order: 0',
		'---',
		'',
		GENERATED_NOTE,
		'',
		'Each template is written once and assembled for your baseline. Download the ready-to-adopt edition to fill in, or the annotated edition to learn why each section exists. Templates are dedicated to the public domain under [CC0 1.0](https://creativecommons.org/publicdomain/zero/1.0/): adopt and change them without attribution. They are not legal advice; tailor them before adoption.',
		'',
		`**Download the full kit:** [every template, in Word and Markdown, with the decision worksheets (.zip)](/downloads/${KIT_FILE}).`,
		'',
		...groups.flatMap((g) => [g, '']),
	].join('\n');
}

// Worksheet baselines: the security baselines when a family control is in one
// (PT has none), plus Privacy when a family control is in it.
// An organization-wide family has one Organization worksheet.
export function worksheetBaselines(family, controls, orgWide = false) {
	if (orgWide) return [ORGANIZATION];
	const privacy = controls.some((c) => c.family === family && c.baselines.includes('Privacy'));
	return [...(inSecurityBaseline(family, controls) ? ['Low', 'Moderate', 'High'] : []), ...(privacy ? ['Privacy'] : [])];
}

// Typical values from every clause of the family.
export const familyTypical = (family, clauses) =>
	Object.assign({}, ...clauses.filter((c) => c.id.startsWith(`policy/${family}/`)).map((c) => c.typical ?? {}));

export function worksheetInput({ family, baseline, clauses, common, catalog, variables }) {
	return {
		family: family.id,
		baseline,
		questions: family.questions ?? [],
		controls: catalog.controls,
		params: catalog.params,
		// The family's common sections give the typical values for its -1 parameters.
		typical: { ...commonTypical(family, common, variables), ...familyTypical(family.id, clauses) },
		// Parameters a clause fixes in its text instead of a field (AC-2's account procedure).
		set: Object.assign({}, ...clauses.filter((c) => c.id.startsWith(`policy/${family.id}/`)).map((c) => c.set ?? {})),
		defaultDecider: variables[family.role]?.label ?? family.role,
	};
}

const cell = (s) => String(s).replace(/\|/g, '\|').replace(/\n/g, ' ');

/** One decision worksheet page per family, showing the Moderate baseline, or the only one (PT: Privacy). */
export function worksheetPage({ family, clauses, common, catalog, variables, version, order }) {
	const orgWide = organizationWide(family);
	const baselines = worksheetBaselines(family.id, catalog.controls, orgWide);
	const shown = orgWide ? ORGANIZATION : baselines.includes(PREVIEW_BASELINE) ? PREVIEW_BASELINE : baselines[0];
	const rows = worksheetRows(worksheetInput({ family, baseline: shown, clauses, common, catalog, variables }));
	const controls = catalog.controls.filter((c) => c.family === family.id && (orgWide || c.baselines.length)).map((c) => c.id);
	const body = [
		facts({ type: 'worksheet', stage: family.stage, status: 'draft', version, basis: catalog.source }),
		'## What it is',
		`Every decision the ${family.title} family asks your organization to make before its policy and procedures can be final: the family's key questions, then each organization-defined parameter of every ${family.id.toUpperCase()} control${orgWide ? '' : ' in the baseline'}, with a typical value where the [${family.title} Policy](/templates/policies/${family.id}/) gives one. Download the spreadsheet, fill the "Your value" column with the people who decide, and carry the values into the policy's highlighted fields.`,
		'Typical values are starting points, not recommendations for every system. "Who decides" defaults to the role accountable for the family policy; many organizations delegate system-level values to the system owner.',
		'## Downloads',
		['| Variant | Spreadsheet |', '| --- | --- |', ...baselines.map((b) => `| ${variantLabel(b)} | [CSV](/downloads/${worksheetFile(family.id, b)}.csv) |`)].join('\n'),
		orgWide ? '## Decisions' : `## Decisions (${shown} baseline)`,
		`${rows.length} decisions.`,
		[
			`| ${WORKSHEET_COLUMNS.slice(0, 4).join(' | ')} |`,
			'| --- | --- | --- | --- |',
			...rows.map((r) => `| ${cell(r.decision)} | ${r.controls.join(', ')} | ${cell(r.typical)} | ${cell(r.decides)} |`),
		].join('\n'),
	].join('\n\n');
	return {
		file: `worksheets/${family.id}.md`,
		text: page({
			title: `${family.title} Decision Worksheet`,
			description: `Every decision the ${family.title} family of NIST SP 800-53 Rev. 5 forces, with typical values and who decides, ${orgWide ? 'for the whole organization' : 'per baseline'}, as a spreadsheet.`,
			label: `${family.title} (${family.id.toUpperCase()})`,
			order,
			controls,
			body,
		}),
		summary: {
			title: `${family.title} Decision Worksheet`,
			href: `/templates/worksheets/${family.id}/`,
			type: 'worksheet',
			stage: family.stage,
			status: 'draft',
		},
	};
}
