// Builds the generated template pages under src/content/docs/templates/
// (PRD TPL-07) and names the download files, so pages and kit agree.
// No file access, so npm test can run it on fixtures.
import { assemblePolicy, policyBaselines } from '../../src/lib/template-assemble.ts';
import { renderBlocks } from '../../src/lib/template-editions.ts';
import { renderVariables } from '../../src/lib/template-vars.ts';

export const GENERATED_NOTE =
	'<!-- Generated by npm run templates from templates/. Edit the sources there, not this page. -->';
export const PREVIEW_BASELINE = 'Moderate';
const EDITION_SUFFIX = { clean: '', annotated: '-annotated' };
const TYPE_LABEL = { policy: 'Policy', plan: 'Plan', standard: 'Standard', procedure: 'Procedure', form: 'Form or register' };
const TYPE_GROUP = { policy: 'Policies', plan: 'Plans', standard: 'Standards', procedure: 'Procedures', form: 'Forms and registers' };

const yaml = (s) => `'${String(s).replace(/'/g, "''")}'`;
const cap = (s) => s.charAt(0).toUpperCase() + s.slice(1);
const controlUrl = (id) => {
	const [base, enh] = id.split('.');
	return `/controls/${base.split('-')[0]}/${base}/${enh ? `#${id}` : ''}`;
};

// Download paths under /downloads/, without extension.
export const policyFile = (family, baseline, edition) =>
	`policies/${family}-policy-${baseline.toLowerCase()}${EDITION_SUFFIX[edition]}`;
export const templateFile = (id, edition) => `${id}${EDITION_SUFFIX[edition]}`;

// Site preview: annotated edition, headings one level down under "## Preview",
// without the document's own title.
export function preview(source, ctx) {
	return renderVariables(renderBlocks(source, 'annotated', 'site'), ctx, 'site')
		.replace(/^# .*\n+/, '')
		.replace(/^(#{1,5}) /gm, '#$1 ')
		.trim();
}

function facts({ type, stage, status, version, basis }) {
	return [
		'| Type | Program stage | Status | Template version | NIST basis |',
		'| --- | --- | --- | --- | --- |',
		`| ${TYPE_LABEL[type]} | ${cap(stage)} | ${cap(status)} | ${version} | ${basis} |`,
	].join('\n');
}

function page({ title, description, label, order, controls, body }) {
	return [
		'---',
		`title: ${yaml(title)}`,
		`description: ${yaml(description)}`,
		'sidebar:',
		`  label: ${yaml(label)}`,
		`  order: ${order}`,
		`controls: [${controls.join(', ')}]`,
		'---',
		'',
		GENERATED_NOTE,
		'',
		body.trim(),
		'',
	].join('\n');
}

function downloadRows(rows) {
	return [
		'| Variant | Ready to adopt | Annotated |',
		'| --- | --- | --- |',
		...rows.map(({ label, file }) => `| ${label} | [Markdown](/downloads/${file('clean')}.md) | [Markdown](/downloads/${file('annotated')}.md) |`),
	].join('\n');
}

/**
 * One family policy page: facts, what it is, controls, decisions, downloads per
 * baseline, and an annotated preview at the Moderate baseline.
 */
export function policyPage({ family, clauses, common, catalog, variables, version, order }) {
	const own = clauses.filter((c) => c.id.startsWith(`policy/${family.id}/`));
	const baselines = policyBaselines(family.id, own, catalog.controls);
	const byId = new Map(catalog.controls.map((c) => [c.id, c]));
	const policyControl = byId.get(`${family.id}-1`);
	const fam = family.id.toUpperCase();
	const variants = Object.fromEntries(
		baselines.map((b) => [b, assemblePolicy({ common: common.body, family, clauses: own, controls: catalog.controls, baseline: b })]),
	);
	const shown = variants[PREVIEW_BASELINE] ?? Object.values(variants)[0];
	const shownBaseline = variants[PREVIEW_BASELINE] ? PREVIEW_BASELINE : baselines[0];
	const covered = [...new Set(Object.values(variants).flatMap((v) => v.controls))].sort(
		(a, b) => catalog.controls.findIndex((c) => c.id === a) - catalog.controls.findIndex((c) => c.id === b),
	);
	const params = new Set(
		covered.flatMap((id) => byId.get(id).params.filter((p) => !catalog.params[p].aggregates)),
	);
	const status = own.length && own.every((c) => c.status === 'reviewed') && common.data.status === 'reviewed' ? 'reviewed' : 'draft';

	const tick = (id, b) => (variants[b]?.controls.includes(id) ? 'Yes' : '');
	const controlRows = covered.map((id) => {
		const c = byId.get(id);
		return `| [${c.label}](${controlUrl(id)}) | ${c.title} | ${['Low', 'Moderate', 'High', 'Privacy'].map((b) => tick(id, b)).join(' | ')} |`;
	});

	const questions = family.questions?.length
		? [
				'| Decision | Controls | Typical | Who decides |',
				'| --- | --- | --- | --- |',
				...family.questions.map(
					(q) =>
						`| ${q.question} | ${q.controls.map((id) => `[${byId.get(id).label}](${controlUrl(id)})`).join(', ')} | ${q.typical ?? ''} | ${q.decides} |`,
				),
			].join('\n')
		: '';

	const body = [
		facts({ type: 'policy', stage: family.stage, status, version, basis: catalog.source }),
		'## What it is',
		`The ${family.title} policy states what the organization requires for ${family.title.toLowerCase()} and who is accountable for it. It meets [${policyControl.label}](${controlUrl(policyControl.id)}) through the sections every family policy shares, and adds one statement group per control. Each baseline variant includes only the controls in that baseline, taken from the NIST SP 800-53B profiles.`,
		'Adopt the ready-to-adopt edition: fill every highlighted field, delete any "Federal systems" section that does not apply, and have the accountable official approve it. The annotated edition adds guidance on why each section exists and what assessors look for.',
		'## Controls satisfied',
		`"Yes" marks the baseline variants that include the control's statements. ${policyControl.label} is met by the common sections.`,
		['| Control | Title | Low | Moderate | High | Privacy |', '| --- | --- | --- | --- | --- | --- |', ...controlRows].join('\n'),
		'## Decisions to make first',
		`The policy has ${params.size} organization-defined parameters across all variants; each appears as a highlighted field with its typical value where one is given. Settle these first:`,
		questions || `No family-level decisions are recorded yet beyond the parameters.`,
		'## Downloads',
		downloadRows(baselines.map((b) => ({ label: b, file: (e) => policyFile(family.id, b, e) }))),
		`## Preview (${shownBaseline} baseline, annotated)`,
		preview(shown.source, { variables, params: catalog.params, typical: shown.typical, family }),
	]
		.filter(Boolean)
		.join('\n\n');

	return {
		file: `policies/${family.id}.md`,
		text: page({
			title: `${family.title} Policy`,
			description: `Ready-to-adopt ${family.title} policy template for NIST SP 800-53 Rev. 5, with a statement group for each control and a variant per baseline (${baselines.join(', ')}).`,
			label: `${family.title} (${fam})`,
			order,
			controls: covered,
			body,
		}),
		summary: { title: `${family.title} Policy`, href: `/templates/policies/${family.id}/`, type: 'policy', stage: family.stage, status },
	};
}

/** One page for a plan, standard, procedure or form. */
export function templatePage({ template, catalog, variables, version, order }) {
	const byId = new Map(catalog.controls.map((c) => [c.id, c]));
	const rows = template.controls.map((id) => `| [${byId.get(id).label}](${controlUrl(id)}) | ${byId.get(id).title} |`);
	const body = [
		facts({ type: template.type, stage: template.stage, status: template.status, version, basis: catalog.source }),
		'## What it is',
		template.description,
		'## Controls satisfied',
		['| Control | Title |', '| --- | --- |', ...rows].join('\n'),
		template.ssdf?.length ? `**SSDF practices:** ${template.ssdf.join(', ')}` : '',
		'## Downloads',
		downloadRows([{ label: 'All baselines', file: (e) => templateFile(template.id, e) }]),
		'## Preview (annotated)',
		preview(template.body, { variables, params: catalog.params, typical: template.typical }),
	]
		.filter(Boolean)
		.join('\n\n');
	const [folder, ...rest] = template.id.split('/');
	return {
		file: `${template.id}.md`,
		text: page({
			title: template.title,
			description: template.description,
			label: template.title,
			order,
			controls: template.controls,
			body,
		}),
		summary: { title: template.title, href: `/templates/${folder}/${rest.join('/')}/`, type: template.type, stage: template.stage, status: template.status },
	};
}

/** The templates index: every generated page, grouped by type. */
export function indexPage(summaries) {
	const groups = ['policy', 'plan', 'procedure', 'standard', 'form']
		.map((type) => {
			const list = summaries.filter((s) => s.type === type);
			if (!list.length) return '';
			return [
				`## ${TYPE_GROUP[type]}`,
				['| Template | Program stage | Status |', '| --- | --- | --- |', ...list.map((s) => `| [${s.title}](${s.href}) | ${cap(s.stage)} | ${cap(s.status)} |`)].join('\n'),
			].join('\n\n');
		})
		.filter(Boolean);
	return [
		'---',
		"title: 'Templates'",
		"description: 'Ready-to-adopt security program templates for NIST SP 800-53 Rev. 5: family policies per baseline, plans, procedures, standards and forms. CC0.'",
		'sidebar:',
		"  label: 'All templates'",
		'  order: 0',
		'---',
		'',
		GENERATED_NOTE,
		'',
		'Each template is written once and assembled for your baseline. Download the ready-to-adopt edition to fill in, or the annotated edition to learn why each section exists. Templates are dedicated to the public domain under [CC0 1.0](https://creativecommons.org/publicdomain/zero/1.0/): adopt and change them without attribution. They are not legal advice; tailor them before adoption.',
		'',
		...groups.flatMap((g) => [g, '']),
	].join('\n');
}
